spring:
  application:
    name: service-discovery1
#单个配置
server:
  port: 1001
eureka:
  server:
    enable-self-preservation: true  #eureka自我保护机制
  instance:
    hostname: service-discovery1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://service-discovery1:1001/eureka/





